version: '3.7'
services:
  db:
      image: postgres
      restart: always
      ports:
        - 3306:3306
      volumes:
        - ./data:/var/lib/postgres
      environment:
        POSTGRES_PASSWORD: example
        POSTGRES_USER: postgre
        POSTGRES_DATABASE: db